[2025-03-30T04:01:24.988+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fetch_aqi_multiple_cities.fetch_aqi_all_cities scheduled__2025-03-30T03:00:00+00:00 [queued]>
[2025-03-30T04:01:24.991+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fetch_aqi_multiple_cities.fetch_aqi_all_cities scheduled__2025-03-30T03:00:00+00:00 [queued]>
[2025-03-30T04:01:24.991+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-03-30T04:01:24.995+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): fetch_aqi_all_cities> on 2025-03-30 03:00:00+00:00
[2025-03-30T04:01:24.997+0000] {standard_task_runner.py:60} INFO - Started process 30749 to run task
[2025-03-30T04:01:24.998+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'fetch_aqi_multiple_cities', 'fetch_aqi_all_cities', 'scheduled__2025-03-30T03:00:00+00:00', '--job-id', '122', '--raw', '--subdir', 'DAGS_FOLDER/fetch_multiple_cities.py', '--cfg-path', '/tmp/tmptz9aa71w']
[2025-03-30T04:01:24.999+0000] {standard_task_runner.py:88} INFO - Job 122: Subtask fetch_aqi_all_cities
[2025-03-30T04:01:25.005+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-03-30T04:01:25.016+0000] {task_command.py:423} INFO - Running <TaskInstance: fetch_aqi_multiple_cities.fetch_aqi_all_cities scheduled__2025-03-30T03:00:00+00:00 [running]> on host f5300fe43025
[2025-03-30T04:01:25.042+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='fetch_aqi_multiple_cities' AIRFLOW_CTX_TASK_ID='fetch_aqi_all_cities' AIRFLOW_CTX_EXECUTION_DATE='2025-03-30T03:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-30T03:00:00+00:00'
[2025-03-30T04:01:31.054+0000] {fetch_multiple_cities.py:62} ERROR - ⚠️ Error fetching data for Bangkok: HTTPConnectionPool(host='api.airvisual.com', port=80): Max retries exceeded with url: /v2/city?city=Bangkok&state=Bangkok&country=Thailand&key=4fb76e79-4433-4b76-9866-f8fdf19a9d33 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffff8ed1ac70>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2025-03-30T04:01:46.081+0000] {fetch_multiple_cities.py:62} ERROR - ⚠️ Error fetching data for Chiang Mai: HTTPConnectionPool(host='api.airvisual.com', port=80): Max retries exceeded with url: /v2/city?city=Chiang%20Mai&state=Chiang%20Mai&country=Thailand&key=4fb76e79-4433-4b76-9866-f8fdf19a9d33 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffff8ed1aa00>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2025-03-30T05:24:23.775+0000] {fetch_multiple_cities.py:62} ERROR - ⚠️ Error fetching data for Ratchaburi: HTTPConnectionPool(host='api.airvisual.com', port=80): Max retries exceeded with url: /v2/city?city=Ratchaburi&state=Ratchaburi&country=Thailand&key=4fb76e79-4433-4b76-9866-f8fdf19a9d33 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffff8ed1aee0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2025-03-30T05:24:38.799+0000] {fetch_multiple_cities.py:62} ERROR - ⚠️ Error fetching data for Rua Yai: HTTPConnectionPool(host='api.airvisual.com', port=80): Max retries exceeded with url: /v2/city?city=Rua%20Yai&state=Suphan%20Buri&country=Thailand&key=4fb76e79-4433-4b76-9866-f8fdf19a9d33 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffff8ed1afd0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2025-03-30T06:33:21.670+0000] {fetch_multiple_cities.py:62} ERROR - ⚠️ Error fetching data for Mueang Nonthaburi: HTTPConnectionPool(host='api.airvisual.com', port=80): Max retries exceeded with url: /v2/city?city=Mueang%20Nonthaburi&state=Nonthaburi&country=Thailand&key=4fb76e79-4433-4b76-9866-f8fdf19a9d33 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffff8ed1ad30>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2025-03-30T06:33:36.674+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-03-30T06:33:36.688+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=fetch_aqi_multiple_cities, task_id=fetch_aqi_all_cities, execution_date=20250330T030000, start_date=20250330T040124, end_date=20250330T063336
[2025-03-30T06:33:36.747+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-03-30T06:33:36.759+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
