[2025-03-29T00:10:07.689+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: validate_aqi_data.validate_aqi scheduled__2025-03-28T00:00:00+00:00 [queued]>
[2025-03-29T00:10:07.693+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: validate_aqi_data.validate_aqi scheduled__2025-03-28T00:00:00+00:00 [queued]>
[2025-03-29T00:10:07.693+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-03-29T00:10:07.704+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): validate_aqi> on 2025-03-28 00:00:00+00:00
[2025-03-29T00:10:07.707+0000] {standard_task_runner.py:60} INFO - Started process 13391 to run task
[2025-03-29T00:10:07.709+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'validate_aqi_data', 'validate_aqi', 'scheduled__2025-03-28T00:00:00+00:00', '--job-id', '91', '--raw', '--subdir', 'DAGS_FOLDER/validate_aqi_data.py', '--cfg-path', '/tmp/tmp4ux08qde']
[2025-03-29T00:10:07.710+0000] {standard_task_runner.py:88} INFO - Job 91: Subtask validate_aqi
[2025-03-29T00:10:07.718+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-03-29T00:10:07.738+0000] {task_command.py:423} INFO - Running <TaskInstance: validate_aqi_data.validate_aqi scheduled__2025-03-28T00:00:00+00:00 [running]> on host f5300fe43025
[2025-03-29T00:10:07.796+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='validate_aqi_data' AIRFLOW_CTX_TASK_ID='validate_aqi' AIRFLOW_CTX_EXECUTION_DATE='2025-03-28T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-28T00:00:00+00:00'
[2025-03-29T00:10:07.806+0000] {base.py:83} INFO - Using connection ID 'postgres_conn' for task execution.
[2025-03-29T00:10:07.811+0000] {validate_aqi_data.py:55} INFO - ✅ Data validation ผ่านทั้งหมด
[2025-03-29T00:10:07.811+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-03-29T00:10:07.818+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=validate_aqi_data, task_id=validate_aqi, execution_date=20250328T000000, start_date=20250329T001007, end_date=20250329T001007
[2025-03-29T00:10:07.849+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-03-29T00:10:07.858+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
