[2025-03-27T09:01:56.346+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fetch_aqi_multiple_cities.fetch_aqi_all_cities scheduled__2025-03-27T08:00:00+00:00 [queued]>
[2025-03-27T09:01:56.352+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fetch_aqi_multiple_cities.fetch_aqi_all_cities scheduled__2025-03-27T08:00:00+00:00 [queued]>
[2025-03-27T09:01:56.352+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-03-27T09:01:56.360+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): fetch_aqi_all_cities> on 2025-03-27 08:00:00+00:00
[2025-03-27T09:01:56.362+0000] {standard_task_runner.py:60} INFO - Started process 1834 to run task
[2025-03-27T09:01:56.365+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'fetch_aqi_multiple_cities', 'fetch_aqi_all_cities', 'scheduled__2025-03-27T08:00:00+00:00', '--job-id', '21', '--raw', '--subdir', 'DAGS_FOLDER/fetch_multiple_cities.py', '--cfg-path', '/tmp/tmp07gl1ws5']
[2025-03-27T09:01:56.367+0000] {standard_task_runner.py:88} INFO - Job 21: Subtask fetch_aqi_all_cities
[2025-03-27T09:01:56.378+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-03-27T09:01:56.402+0000] {task_command.py:423} INFO - Running <TaskInstance: fetch_aqi_multiple_cities.fetch_aqi_all_cities scheduled__2025-03-27T08:00:00+00:00 [running]> on host 79a5714298e2
[2025-03-27T09:01:56.446+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='fetch_aqi_multiple_cities' AIRFLOW_CTX_TASK_ID='fetch_aqi_all_cities' AIRFLOW_CTX_EXECUTION_DATE='2025-03-27T08:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-27T08:00:00+00:00'
[2025-03-27T09:01:56.453+0000] {fetch_multiple_cities.py:61} ERROR - ⚠️ Error fetching data for Bangkok: HTTPConnectionPool(host='api.airvisual.com', port=80): Max retries exceeded with url: /v2/city?city=Bangkok&state=Bangkok&country=Thailand&key=4fb76e79-4433-4b76-9866-f8fdf19a9d33 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffff7b1d97f0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2025-03-27T09:01:56.456+0000] {fetch_multiple_cities.py:61} ERROR - ⚠️ Error fetching data for Chiang Mai: HTTPConnectionPool(host='api.airvisual.com', port=80): Max retries exceeded with url: /v2/city?city=Chiang%20Mai&state=Chiang%20Mai&country=Thailand&key=4fb76e79-4433-4b76-9866-f8fdf19a9d33 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffff7b1d9850>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2025-03-27T09:01:56.459+0000] {fetch_multiple_cities.py:61} ERROR - ⚠️ Error fetching data for Ratchaburi: HTTPConnectionPool(host='api.airvisual.com', port=80): Max retries exceeded with url: /v2/city?city=Ratchaburi&state=Ratchaburi&country=Thailand&key=4fb76e79-4433-4b76-9866-f8fdf19a9d33 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffff7b1d99a0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2025-03-27T09:01:56.463+0000] {fetch_multiple_cities.py:61} ERROR - ⚠️ Error fetching data for Rua Yai: HTTPConnectionPool(host='api.airvisual.com', port=80): Max retries exceeded with url: /v2/city?city=Rua%20Yai&state=Suphan%20Buri&country=Thailand&key=4fb76e79-4433-4b76-9866-f8fdf19a9d33 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffff7b1d97f0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2025-03-27T09:01:56.466+0000] {fetch_multiple_cities.py:61} ERROR - ⚠️ Error fetching data for Mueang Nonthaburi: HTTPConnectionPool(host='api.airvisual.com', port=80): Max retries exceeded with url: /v2/city?city=Mueang%20Nonthaburi&state=Nonthaburi&country=Thailand&key=4fb76e79-4433-4b76-9866-f8fdf19a9d33 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffff7b1d9850>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2025-03-27T09:01:56.467+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-03-27T09:01:56.472+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=fetch_aqi_multiple_cities, task_id=fetch_aqi_all_cities, execution_date=20250327T080000, start_date=20250327T090156, end_date=20250327T090156
[2025-03-27T09:01:56.503+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-03-27T09:01:56.513+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
