[2025-03-30T01:10:25.510+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fetch_aqi_multiple_cities.fetch_aqi_all_cities scheduled__2025-03-30T00:00:00+00:00 [queued]>
[2025-03-30T01:10:25.514+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fetch_aqi_multiple_cities.fetch_aqi_all_cities scheduled__2025-03-30T00:00:00+00:00 [queued]>
[2025-03-30T01:10:25.514+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-03-30T01:10:25.519+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): fetch_aqi_all_cities> on 2025-03-30 00:00:00+00:00
[2025-03-30T01:10:25.521+0000] {standard_task_runner.py:60} INFO - Started process 26603 to run task
[2025-03-30T01:10:25.523+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'fetch_aqi_multiple_cities', 'fetch_aqi_all_cities', 'scheduled__2025-03-30T00:00:00+00:00', '--job-id', '119', '--raw', '--subdir', 'DAGS_FOLDER/fetch_multiple_cities.py', '--cfg-path', '/tmp/tmp__tmje2j']
[2025-03-30T01:10:25.524+0000] {standard_task_runner.py:88} INFO - Job 119: Subtask fetch_aqi_all_cities
[2025-03-30T01:10:25.531+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-03-30T01:10:25.546+0000] {task_command.py:423} INFO - Running <TaskInstance: fetch_aqi_multiple_cities.fetch_aqi_all_cities scheduled__2025-03-30T00:00:00+00:00 [running]> on host f5300fe43025
[2025-03-30T01:10:25.585+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='fetch_aqi_multiple_cities' AIRFLOW_CTX_TASK_ID='fetch_aqi_all_cities' AIRFLOW_CTX_EXECUTION_DATE='2025-03-30T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-30T00:00:00+00:00'
[2025-03-30T01:10:25.893+0000] {fetch_multiple_cities.py:51} INFO - ✅ Bangkok: AQI = 110
[2025-03-30T01:10:25.897+0000] {base.py:83} INFO - Using connection ID 'postgres_conn' for task execution.
[2025-03-30T01:10:25.898+0000] {sql.py:450} INFO - Running statement: 
                        INSERT INTO air_quality_data (city, aqi, timestamp_utc)
                        VALUES (%s, %s, %s);
                    , parameters: ('Bangkok', 110, datetime.datetime(2025, 3, 30, 8, 10, 25, 586585, tzinfo=<DstTzInfo 'Asia/Bangkok' +07+7:00:00 STD>))
[2025-03-30T01:10:25.899+0000] {sql.py:459} INFO - Rows affected: 1
[2025-03-30T01:10:41.181+0000] {fetch_multiple_cities.py:51} INFO - ✅ Chiang Mai: AQI = 187
[2025-03-30T01:10:41.190+0000] {base.py:83} INFO - Using connection ID 'postgres_conn' for task execution.
[2025-03-30T01:10:41.193+0000] {sql.py:450} INFO - Running statement: 
                        INSERT INTO air_quality_data (city, aqi, timestamp_utc)
                        VALUES (%s, %s, %s);
                    , parameters: ('Chiang Mai', 187, datetime.datetime(2025, 3, 30, 8, 10, 25, 586585, tzinfo=<DstTzInfo 'Asia/Bangkok' +07+7:00:00 STD>))
[2025-03-30T01:10:41.193+0000] {sql.py:459} INFO - Rows affected: 1
[2025-03-30T01:27:34.279+0000] {fetch_multiple_cities.py:51} INFO - ✅ Ratchaburi: AQI = 82
[2025-03-30T01:27:34.288+0000] {base.py:83} INFO - Using connection ID 'postgres_conn' for task execution.
[2025-03-30T01:27:34.291+0000] {sql.py:450} INFO - Running statement: 
                        INSERT INTO air_quality_data (city, aqi, timestamp_utc)
                        VALUES (%s, %s, %s);
                    , parameters: ('Ratchaburi', 82, datetime.datetime(2025, 3, 30, 8, 10, 25, 586585, tzinfo=<DstTzInfo 'Asia/Bangkok' +07+7:00:00 STD>))
[2025-03-30T01:27:34.292+0000] {sql.py:459} INFO - Rows affected: 1
[2025-03-30T01:27:38.477+0000] {local_task_job_runner.py:302} WARNING - State of this instance has been externally set to up_for_retry. Terminating instance.
[2025-03-30T01:27:38.479+0000] {process_utils.py:131} INFO - Sending 15 to group 26603. PIDs of all processes in the group: [26603]
[2025-03-30T01:27:38.480+0000] {process_utils.py:86} INFO - Sending the signal 15 to group 26603
[2025-03-30T01:27:38.480+0000] {taskinstance.py:2450} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-03-30T01:27:38.486+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/fetch_multiple_cities.py", line 65, in fetch_and_insert_multiple
    time.sleep(15)  # 2 วินาทีต่อเมือง (ปรับได้)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2452, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2025-03-30T01:27:38.489+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=fetch_aqi_multiple_cities, task_id=fetch_aqi_all_cities, execution_date=20250330T000000, start_date=20250330T011025, end_date=20250330T012738
[2025-03-30T01:27:38.496+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 119 for task fetch_aqi_all_cities (Task received SIGTERM signal; 26603)
[2025-03-30T01:27:38.511+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=26603, status='terminated', exitcode=1, started='01:10:25') (26603) terminated with exit code 1
