[2025-03-30T06:33:15.346+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fetch_aqi_multiple_cities.fetch_aqi_all_cities scheduled__2025-03-30T05:00:00+00:00 [queued]>
[2025-03-30T06:33:15.350+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fetch_aqi_multiple_cities.fetch_aqi_all_cities scheduled__2025-03-30T05:00:00+00:00 [queued]>
[2025-03-30T06:33:15.350+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-03-30T06:33:15.357+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): fetch_aqi_all_cities> on 2025-03-30 05:00:00+00:00
[2025-03-30T06:33:15.360+0000] {standard_task_runner.py:60} INFO - Started process 30845 to run task
[2025-03-30T06:33:15.362+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'fetch_aqi_multiple_cities', 'fetch_aqi_all_cities', 'scheduled__2025-03-30T05:00:00+00:00', '--job-id', '124', '--raw', '--subdir', 'DAGS_FOLDER/fetch_multiple_cities.py', '--cfg-path', '/tmp/tmpki0s1kjj']
[2025-03-30T06:33:15.364+0000] {standard_task_runner.py:88} INFO - Job 124: Subtask fetch_aqi_all_cities
[2025-03-30T06:33:15.372+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-03-30T06:33:15.398+0000] {task_command.py:423} INFO - Running <TaskInstance: fetch_aqi_multiple_cities.fetch_aqi_all_cities scheduled__2025-03-30T05:00:00+00:00 [running]> on host f5300fe43025
[2025-03-30T06:33:15.433+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='fetch_aqi_multiple_cities' AIRFLOW_CTX_TASK_ID='fetch_aqi_all_cities' AIRFLOW_CTX_EXECUTION_DATE='2025-03-30T05:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-30T05:00:00+00:00'
[2025-03-30T06:33:15.437+0000] {fetch_multiple_cities.py:62} ERROR - ⚠️ Error fetching data for Bangkok: HTTPConnectionPool(host='api.airvisual.com', port=80): Max retries exceeded with url: /v2/city?city=Bangkok&state=Bangkok&country=Thailand&key=4fb76e79-4433-4b76-9866-f8fdf19a9d33 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffff8ed1adc0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2025-03-30T06:33:30.463+0000] {fetch_multiple_cities.py:62} ERROR - ⚠️ Error fetching data for Chiang Mai: HTTPConnectionPool(host='api.airvisual.com', port=80): Max retries exceeded with url: /v2/city?city=Chiang%20Mai&state=Chiang%20Mai&country=Thailand&key=4fb76e79-4433-4b76-9866-f8fdf19a9d33 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffff8ed1af70>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2025-03-30T07:15:51.097+0000] {fetch_multiple_cities.py:62} ERROR - ⚠️ Error fetching data for Ratchaburi: HTTPConnectionPool(host='api.airvisual.com', port=80): Max retries exceeded with url: /v2/city?city=Ratchaburi&state=Ratchaburi&country=Thailand&key=4fb76e79-4433-4b76-9866-f8fdf19a9d33 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffff8ed1a190>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2025-03-30T07:16:06.112+0000] {fetch_multiple_cities.py:62} ERROR - ⚠️ Error fetching data for Rua Yai: HTTPConnectionPool(host='api.airvisual.com', port=80): Max retries exceeded with url: /v2/city?city=Rua%20Yai&state=Suphan%20Buri&country=Thailand&key=4fb76e79-4433-4b76-9866-f8fdf19a9d33 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffff8ed1aa60>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2025-03-30T08:33:58.957+0000] {fetch_multiple_cities.py:62} ERROR - ⚠️ Error fetching data for Mueang Nonthaburi: HTTPConnectionPool(host='api.airvisual.com', port=80): Max retries exceeded with url: /v2/city?city=Mueang%20Nonthaburi&state=Nonthaburi&country=Thailand&key=4fb76e79-4433-4b76-9866-f8fdf19a9d33 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffff8ed1ac70>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2025-03-30T08:34:13.976+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-03-30T08:34:13.988+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=fetch_aqi_multiple_cities, task_id=fetch_aqi_all_cities, execution_date=20250330T050000, start_date=20250330T063315, end_date=20250330T083413
[2025-03-30T08:34:14.042+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-03-30T08:34:14.053+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
