[2025-03-30T09:34:15.752+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fetch_aqi_multiple_cities.fetch_aqi_all_cities scheduled__2025-03-30T08:00:00+00:00 [queued]>
[2025-03-30T09:34:15.756+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fetch_aqi_multiple_cities.fetch_aqi_all_cities scheduled__2025-03-30T08:00:00+00:00 [queued]>
[2025-03-30T09:34:15.756+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-03-30T09:34:15.761+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): fetch_aqi_all_cities> on 2025-03-30 08:00:00+00:00
[2025-03-30T09:34:15.764+0000] {standard_task_runner.py:60} INFO - Started process 30913 to run task
[2025-03-30T09:34:15.765+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'fetch_aqi_multiple_cities', 'fetch_aqi_all_cities', 'scheduled__2025-03-30T08:00:00+00:00', '--job-id', '127', '--raw', '--subdir', 'DAGS_FOLDER/fetch_multiple_cities.py', '--cfg-path', '/tmp/tmpvcbvqdae']
[2025-03-30T09:34:15.767+0000] {standard_task_runner.py:88} INFO - Job 127: Subtask fetch_aqi_all_cities
[2025-03-30T09:34:15.774+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-03-30T09:34:15.790+0000] {task_command.py:423} INFO - Running <TaskInstance: fetch_aqi_multiple_cities.fetch_aqi_all_cities scheduled__2025-03-30T08:00:00+00:00 [running]> on host f5300fe43025
[2025-03-30T09:34:15.824+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='fetch_aqi_multiple_cities' AIRFLOW_CTX_TASK_ID='fetch_aqi_all_cities' AIRFLOW_CTX_EXECUTION_DATE='2025-03-30T08:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-30T08:00:00+00:00'
[2025-03-30T09:34:15.828+0000] {fetch_multiple_cities.py:62} ERROR - ⚠️ Error fetching data for Bangkok: HTTPConnectionPool(host='api.airvisual.com', port=80): Max retries exceeded with url: /v2/city?city=Bangkok&state=Bangkok&country=Thailand&key=4fb76e79-4433-4b76-9866-f8fdf19a9d33 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffff8ed28490>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2025-03-30T09:34:30.865+0000] {fetch_multiple_cities.py:62} ERROR - ⚠️ Error fetching data for Chiang Mai: HTTPConnectionPool(host='api.airvisual.com', port=80): Max retries exceeded with url: /v2/city?city=Chiang%20Mai&state=Chiang%20Mai&country=Thailand&key=4fb76e79-4433-4b76-9866-f8fdf19a9d33 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffff8ed28070>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2025-03-30T10:35:19.534+0000] {fetch_multiple_cities.py:62} ERROR - ⚠️ Error fetching data for Ratchaburi: HTTPConnectionPool(host='api.airvisual.com', port=80): Max retries exceeded with url: /v2/city?city=Ratchaburi&state=Ratchaburi&country=Thailand&key=4fb76e79-4433-4b76-9866-f8fdf19a9d33 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffff8ed282b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
[2025-03-30T10:35:34.961+0000] {fetch_multiple_cities.py:51} INFO - ✅ Rua Yai: AQI = 110
[2025-03-30T10:35:34.973+0000] {base.py:83} INFO - Using connection ID 'postgres_conn' for task execution.
[2025-03-30T10:35:34.977+0000] {sql.py:450} INFO - Running statement: 
                        INSERT INTO air_quality_data (city, aqi, timestamp_utc)
                        VALUES (%s, %s, %s);
                    , parameters: ('Rua Yai', 110, datetime.datetime(2025, 3, 30, 16, 34, 15, 825277, tzinfo=<DstTzInfo 'Asia/Bangkok' +07+7:00:00 STD>))
[2025-03-30T10:35:34.979+0000] {sql.py:459} INFO - Rows affected: 1
[2025-03-30T11:05:33.886+0000] {fetch_multiple_cities.py:51} INFO - ✅ Mueang Nonthaburi: AQI = 90
[2025-03-30T11:05:33.889+0000] {base.py:83} INFO - Using connection ID 'postgres_conn' for task execution.
[2025-03-30T11:05:33.890+0000] {sql.py:450} INFO - Running statement: 
                        INSERT INTO air_quality_data (city, aqi, timestamp_utc)
                        VALUES (%s, %s, %s);
                    , parameters: ('Mueang Nonthaburi', 90, datetime.datetime(2025, 3, 30, 16, 34, 15, 825277, tzinfo=<DstTzInfo 'Asia/Bangkok' +07+7:00:00 STD>))
[2025-03-30T11:05:33.891+0000] {sql.py:459} INFO - Rows affected: 1
[2025-03-30T11:05:48.909+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-03-30T11:05:48.923+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=fetch_aqi_multiple_cities, task_id=fetch_aqi_all_cities, execution_date=20250330T080000, start_date=20250330T093415, end_date=20250330T110548
[2025-03-30T11:05:48.975+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-03-30T11:05:48.986+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
