[2025-03-29T14:06:29.840+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fetch_aqi_multiple_cities.fetch_aqi_all_cities scheduled__2025-03-29T13:00:00+00:00 [queued]>
[2025-03-29T14:06:29.842+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fetch_aqi_multiple_cities.fetch_aqi_all_cities scheduled__2025-03-29T13:00:00+00:00 [queued]>
[2025-03-29T14:06:29.842+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-03-29T14:06:29.847+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): fetch_aqi_all_cities> on 2025-03-29 13:00:00+00:00
[2025-03-29T14:06:29.848+0000] {standard_task_runner.py:60} INFO - Started process 23965 to run task
[2025-03-29T14:06:29.850+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'fetch_aqi_multiple_cities', 'fetch_aqi_all_cities', 'scheduled__2025-03-29T13:00:00+00:00', '--job-id', '106', '--raw', '--subdir', 'DAGS_FOLDER/fetch_multiple_cities.py', '--cfg-path', '/tmp/tmpvhmsl82m']
[2025-03-29T14:06:29.850+0000] {standard_task_runner.py:88} INFO - Job 106: Subtask fetch_aqi_all_cities
[2025-03-29T14:06:29.856+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-03-29T14:06:29.866+0000] {task_command.py:423} INFO - Running <TaskInstance: fetch_aqi_multiple_cities.fetch_aqi_all_cities scheduled__2025-03-29T13:00:00+00:00 [running]> on host f5300fe43025
[2025-03-29T14:06:29.892+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='fetch_aqi_multiple_cities' AIRFLOW_CTX_TASK_ID='fetch_aqi_all_cities' AIRFLOW_CTX_EXECUTION_DATE='2025-03-29T13:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-29T13:00:00+00:00'
[2025-03-29T14:06:30.172+0000] {fetch_multiple_cities.py:51} INFO - ✅ Bangkok: AQI = 112
[2025-03-29T14:06:30.182+0000] {base.py:83} INFO - Using connection ID 'postgres_conn' for task execution.
[2025-03-29T14:06:30.185+0000] {sql.py:450} INFO - Running statement: 
                        INSERT INTO air_quality_data (city, aqi, timestamp_utc)
                        VALUES (%s, %s, %s);
                    , parameters: ('Bangkok', 112, datetime.datetime(2025, 3, 29, 21, 6, 29, 893593, tzinfo=<DstTzInfo 'Asia/Bangkok' +07+7:00:00 STD>))
[2025-03-29T14:06:30.186+0000] {sql.py:459} INFO - Rows affected: 1
[2025-03-29T14:06:45.612+0000] {fetch_multiple_cities.py:51} INFO - ✅ Chiang Mai: AQI = 176
[2025-03-29T14:06:45.625+0000] {base.py:83} INFO - Using connection ID 'postgres_conn' for task execution.
[2025-03-29T14:06:45.630+0000] {sql.py:450} INFO - Running statement: 
                        INSERT INTO air_quality_data (city, aqi, timestamp_utc)
                        VALUES (%s, %s, %s);
                    , parameters: ('Chiang Mai', 176, datetime.datetime(2025, 3, 29, 21, 6, 29, 893593, tzinfo=<DstTzInfo 'Asia/Bangkok' +07+7:00:00 STD>))
[2025-03-29T14:06:45.631+0000] {sql.py:459} INFO - Rows affected: 1
[2025-03-29T14:23:53.890+0000] {fetch_multiple_cities.py:51} INFO - ✅ Ratchaburi: AQI = 69
[2025-03-29T14:23:53.902+0000] {base.py:83} INFO - Using connection ID 'postgres_conn' for task execution.
[2025-03-29T14:23:53.907+0000] {sql.py:450} INFO - Running statement: 
                        INSERT INTO air_quality_data (city, aqi, timestamp_utc)
                        VALUES (%s, %s, %s);
                    , parameters: ('Ratchaburi', 69, datetime.datetime(2025, 3, 29, 21, 6, 29, 893593, tzinfo=<DstTzInfo 'Asia/Bangkok' +07+7:00:00 STD>))
[2025-03-29T14:23:53.908+0000] {sql.py:459} INFO - Rows affected: 1
[2025-03-29T14:23:58.105+0000] {local_task_job_runner.py:302} WARNING - State of this instance has been externally set to up_for_retry. Terminating instance.
[2025-03-29T14:23:58.107+0000] {process_utils.py:131} INFO - Sending 15 to group 23965. PIDs of all processes in the group: [23965]
[2025-03-29T14:23:58.108+0000] {process_utils.py:86} INFO - Sending the signal 15 to group 23965
[2025-03-29T14:23:58.108+0000] {taskinstance.py:2450} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-03-29T14:23:58.115+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/fetch_multiple_cities.py", line 65, in fetch_and_insert_multiple
    time.sleep(15)  # 2 วินาทีต่อเมือง (ปรับได้)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2452, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2025-03-29T14:23:58.117+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=fetch_aqi_multiple_cities, task_id=fetch_aqi_all_cities, execution_date=20250329T130000, start_date=20250329T140629, end_date=20250329T142358
[2025-03-29T14:23:58.124+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 106 for task fetch_aqi_all_cities (Task received SIGTERM signal; 23965)
[2025-03-29T14:23:58.142+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=23965, status='terminated', exitcode=1, started='14:06:29') (23965) terminated with exit code 1
